### ISSUE TITLE
astropy.visualization.scale_image has been deprecated since astropy 1.3

### ISSUE THREAD

**Issue by mirca** [KeplerGO/k2mosaic#13]
``astropy.visualization.scale_image`` has been deprecated since ``astropy1.3``, which implies ``k2mosaic`` is not compatible with ``astropy2.0``

**Comment by barentsen** [comment]
This has been fixed in b2c7d494e63ea9ab15947e196f2b577af23a4d52! :party:

**Comment by mirca** [comment]
dope!! :D
