### ISSUE TITLE
URL Scraping Doesn't Work

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/k2mosaic#15]
In the previous version of k2 mosaic you could pass URLs. These would be downloaded and then the mosaic would automatically know where they are. Now k2mosaic breaks as it's looking for a local file.

The list of URLs is generated with the command tpflist. Example:

`$ k2mosaic tpflist 7 65 > list-of-target-pixel-files.txt`

It would be really great to have this feature back.

**Comment by christinahedges** [comment]
Previous version this would work

`k2mosaic mosaic http://archive.stsci.edu/missions/k2/target_pixel_files/c12/200100000/61000/ktwo200161173-c12_lpd-targ.fits.gz`

**Comment by mirca** [comment]
Looks like this doesn't work in v2.0 as well:

```
Installing collected packages: k2mosaic
Successfully installed k2mosaic-2.0.0

k2mosaic mosaic https://archive.stsci.edu/missions/k2/target_pixel_files/c12/200100000/61000/ktwo200161173-c12_lpd-targ.fits.gz
Usage: k2mosaic mosaic [OPTIONS] FILELIST

Error: Invalid value for "filelist": Could not open file: https://archive.stsci.edu/missions/k2/target_pixel_files/c12/200100000/61000/ktwo200161173-c12_lpd-targ.fits.gz: No such file or directory
```
